Forge/config/routes.rb
Rails.application.routes.draw do

  # Landing
  get 'home_page/landing' => 'home_page#landing'
  get 'home_page/landing_body' => 'home_page#landing_body'

  # Anvil
  get 'anvil/show'
  get 'anvil/list'
  get 'anvil/overview'
  get 'anvil/assignment_list' => 'anvil#assignment_list'
  get 'anvil/my_anvil' => 'anvil#my_anvil'
  get 'anvil/:id/assignment' => 'anvil#assignment'
  get 'anvil/getting_started' => 'anvil#getting_started'
  get 'anvil/osx' => 'anvil#gs_osx'
  get 'anvil/win' => 'anvil#gs_win'
  get 'anvil/other' => 'anvil#gs_other'
  get 'anvil/:id/assignment_progress' => 'anvil#assignment_progress'
  get 'anvil/:id/assignment_description' => 'anvil#assignment_description'

  get 'blaze/show'

  get 'flame/show' => 'flame#show'

  get 'minecraft/show'

  get 'students/create'
  get 'students/list'
  get 'students/new'
  get 'account' => 'account#show'
  get 'assignments/create'
  get 'assignments/createLevel'
  get 'assignments/new'
  get 'downloads/:id/proj/(*path)' => 'downloads#proj'
  get 'downloads/flame' => 'downloads#flame'
  get 'login' => 'session#show'
  get 'minecraft_accounts/create'
  get 'minecraft_accounts/list'
  get 'minecraft_accounts/new'
  get 'password' => 'password#show'
  get 'password_change' => 'password#change'
  get 'session_login' => 'session#login'
  get 'session_logout' => 'session#logout'
  post 'service/get_minecraft_session' => 'service#get_minecraft_session'
  post 'service/get_user_level_data' => 'service#get_user_level_data'
  post 'service/get_chat' => 'service#get_chat'
  post 'service/push_chat' => 'service#push_chat'
  match 'blaze/(*path)' => redirect {|params, req| "http://localhost:9886/#{params[:path]}"},  via: [:get, :post]

  resources :minecraft_accounts, :only => [:show, :destroy]
  resources :students, :only => [:show, :destroy]
  resources :assignments, :only => [:show, :destroy]

  root 'anvil#show'
end

Forge/app/controllers/anvil_controller.rb
class AnvilController < ApplicationController

  include SessionHelper
  include ApplicationHelper

  def show
    return if sessionActiveCheckFailed
    render 'show', :layout => false
  end

  def list
    return if sessionActiveCheckFailed
  end

  def overview
    return if sessionActiveCheckFailed
  end

  # Partials
  def getting_started
    render partial: 'getting_started', :layout => false
  end

  def assignment_list
    return if sessionActiveCheckFailed

    @assignmentsData = []
    @assignments = AssignmentDescription.find_each

    # For each Assignment Description
    @assignments.each do |assignment|

      # TODO: These need to be collapsed into a single QUERY with JOINs
      # Get User Assignment
      userAssignment = UserAssignment.find_or_create(sessionGetUser.id, assignment.id)

      possiblePoints = LevelDescription.where(:assignment_description_id => assignment.id).sum(:points)
      earnedPoints = UserLevel.where(:user_assignment_id => userAssignment.id).sum(:points)

      possibleExtraCredit = LevelDescription.where(:assignment_description_id => assignment.id).sum(:extra_credit)
      earnedExtraCredit = UserLevel.where(:user_assignment_id => userAssignment.id).sum(:extra_credit)

      # Build out the 'assignment'
      assignmentData = OpenStruct.new
      assignmentData.assignment = assignment
      assignmentData.isOpen = assignment.open_date < Time.now.getutc
      assignmentData.userAssignment = userAssignment
      assignmentData.possiblePoints = possiblePoints
      assignmentData.earnedPoints = earnedPoints
      assignmentData.possibleExtraCredit = possibleExtraCredit
      assignmentData.earnedExtraCredit = earnedExtraCredit
      assignmentData.pointsPercent = possiblePoints == 0 ?
          '100%' : "#{(zero_divide(Float(earnedPoints), Float(possiblePoints)) * 100).round}%"
      assignmentData.extraCreditPercent = possibleExtraCredit == 0 ?
          '100%' : "#{(zero_divide(Float(earnedExtraCredit), Float(possibleExtraCredit)) * 100).round}%"
      assignmentData.dueDateColorLabel = earnedPoints == possiblePoints ? 'success' : assignment.due_date_color_label
      assignmentData.dueDateColor = earnedPoints == possiblePoints ? 'green' : assignment.due_date_color

      @assignmentsData << assignmentData
    end

    render partial: 'assignment_list', :layout => false
  end

  def assignment
    return if sessionActiveCheckFailed
    @assignment = AssignmentDescription.find(params[:id])
    render partial: 'assignment', :layout => false
  end

  def assignment_description
    return if sessionActiveCheckFailed

    @assignment = AssignmentDescription.find(params[:id])

    if @assignment.nil?
      flash[:error] = "Cannot find an assignment with ID: #{params[:id]}"
      redirect_to assignments_list_path
      return
    end

    @levelDescriptions = LevelDescription.where(:assignment_description_id => @assignment.id).order(levelNumber: :asc)

    # pull User Assignment and all User Levels
    @userAssignment = UserAssignment.find_or_create(sessionGetUser.id, @assignment.id)
    @userLevels = []
    @levels = []
    @levelDescriptions.each do |levelDescription|
      userLevel = UserLevel.find_or_create(@userAssignment.id, levelDescription.id)
      @userLevels << userLevel

      # Build out the 'level'
      level = OpenStruct.new
      level.levelDescription = levelDescription
      level.userLevel = userLevel

      percentage = 100
      if levelDescription.points != 0
        percentage = zero_divide(100 * Float(userLevel.points), Float(levelDescription.points)).round
      end

      case percentage
        when 0..59
          level.panelColor = 'danger'
        when 60..89
          level.panelColor = 'warning'
        else
          level.panelColor = 'success'
      end
      @levels << level

    end

    # Compute assignment level some statistics
    @totalPoints = @earnedPoints = 0
    @levelDescriptions.each do |level| @totalPoints += level.points end
    @userLevels.each do |userLevel| @earnedPoints += userLevel.points end
    @percentage = (100 * zero_divide(Float(@earnedPoints), Float(@totalPoints))).round

    case @percentage
      when 0..59
        @panelColor = 'danger'
      when 60..89
        @panelColor = 'warning'
      else
        @panelColor = 'success'
    end

    render partial: 'assignment_description', :layout => false
  end

  def assignment_progress
    return if sessionActiveCheckFailed

    @assignment = AssignmentDescription.find(params[:id])

    if @assignment.nil?
      flash[:error] = "Cannot find an assignment with ID: #{params[:id]}"
      redirect_to assignments_list_path
      return
    end

    @levelDescriptions = LevelDescription.where(:assignment_description_id => @assignment.id).order(levelNumber: :asc)
    @userAssignment = UserAssignment.find_or_create(sessionGetUser.id, @assignment.id)

    @graphData = []

    @levelDescriptions.each do |levelDescription|
      userLevel = UserLevel.find_or_create(@userAssignment.id, levelDescription.id)

      if userLevel.points > 0
        @graphData << {
            :value => userLevel.points,
            :color =>"#33CC33",
            :highlight => "#00FF00",
            :label => "Level #{levelDescription.levelNumber}, Points"
        }
      end

      # Standard Level
      if levelDescription.extra_credit == 0 and levelDescription.points - userLevel.points > 0
        @graphData << {
            :value => levelDescription.points - userLevel.points,
            :color =>"#F7464A",
            :highlight => "#FF5A5E",
            :label => "Level: #{levelDescription.levelNumber}, Points"
        }
      end

      # Extra Credit Level
      if levelDescription.extra_credit != 0 and levelDescription.extra_credit - userLevel.points > 0
        @graphData << {
            :value => levelDescription.extra_credit - userLevel.points,
            :color =>"#3366FF",
            :highlight => "#6699FF",
            :label => "Level: #{levelDescription.levelNumber}, Points"
        }
      end

      # Sample level (worth no points)
      if levelDescription.extra_credit + levelDescription.points == 0
        @graphData << {
            :value => 5,
            :color =>"#33CC33",
            :highlight => "#00FF00",
            :label => "Sample: #{levelDescription.levelNumber}, Points"
        }
      end

    end

    render partial: 'assignment_progress', :layout => false
  end

  def my_anvil
    render partial: 'my_anvil', :layout => false
  end

  def gs_osx
    render partial: 'gs_osx', :layout => false
  end

  def gs_win
    render partial: 'gs_win', :layout => false
  end

  def gs_other
    render partial: 'gs_other', :layout => false
  end

end

Forge/app/helpers/anvil_helper.rb
module AnvilHelper
end

Forge/app/views/anvil/_assignment.html.erb
<div class="btn-group">

  <!-- Back -->
  <button class="btn btn-default" style="min-width: 75px;" data-async-href="<%=anvil_assignment_list_path%>">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
  </button>

  <!-- Refresh -->
  <button class="btn btn-default" style="min-width: 75px;" data-async-href="<%= "anvil/#{@assignment.id}/assignment" %>">
    <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
  </button>

  <!-- Download -->
  <button style="min-width: 150px;" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    Download <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="#">Python</a></li>
    <li><a class="data-no-turbolink" href=<%= "/downloads/#{@assignment.id}/proj/py_win" %>>Windows</a></li>
    <li><a class="data-no-turbolink" href=<%= "/downloads/#{@assignment.id}/proj/py_osx" %>>Mac OSX</a></li>
    <li role="presentation" class="divider"></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">C++</a></li>
    <li role="presentation"><a class="data-no-turbolink" href=<%= "/downloads/#{@assignment.id}/proj/VS" %>>Visual Studio</a></li>
    <li role="presentation"><a class="data-no-turbolink" href=<%= "/downloads/#{@assignment.id}/proj/XCode" %>>XCode</a></li>
  </ul>
</div>

<div style="text-align: center">
  <h1 class="text-center"><%= @assignment.name %></h1>
</div>


<h4 class="text-center">
  <span class="label label-<%= @assignment.due_date_color %>">
    <%= @assignment.is_past_due ? 'Closed' : @assignment.due_date_countdown %>
  </span>
</h4>

<div style="text-align: center;">
  <br>

  <h3>My Progress</h3>
  <div data-async-url="<%="anvil/#{@assignment.id}/assignment_progress"%>">
    <img style="max-width: 100px; margin-top: 100px; margin-bottom: 100px;" alt="Loading" src=<%= asset_path('Loading.gif') %> />
  </div>
</div>
<br>
<br>

<hr>

<div data-async-url="<%="anvil/#{@assignment.id}/assignment_description"%>">
  <div style="text-align: center;">
    <img style="max-width: 100px; margin-top: 100px; margin-bottom: 100px;" alt="Loading" src=<%= asset_path('Loading.gif') %> />
  </div>
</div>

Forge/app/views/anvil/_assignment_description.html.erb
<% @levels.each do |level| %>
    <div style="margin-top: 30px; margin-left: 15px; margin-right: 15px;">
      <div style='margin-left: 10px; margin-right: 10px;'>

        <a href="#">
          <h4><b><%= level.levelDescription.name %></b></h4>
          <p style='color: red;'>Points: <%= "#{level.userLevel.points} / #{level.levelDescription.points}" %></p>
        </a>

        <div style='margin-left: 20px; background-color:#000000;'>
          <a href="#" style='margin-left: 10px; color:white;'>Python</a>
        </div>
        <div style='margin-left: 20px;'>
          <a href="#" style='margin-left: 10px;'>C++</a>
        </div>
        <div style='margin-left: 20px;'>
          <a href="#" style='margin-left: 10px;'>C#</a>
        </div>
      </div>
      <hr>
    </div>
<% end %>

Forge/app/views/anvil/_assignment_list.html.erb
<div id="async-content-area">
  <div style="text-align: center;">
    <% assignmentsCount = pending_assignments_count %>
    <% if assignmentsCount == 0 %>
        <h2 style="color: green;">You have no upcoming Anvil Assignments.</h2>
    <% else %>
        <h2 style="color: red;">You have unfinished Anvil Assignments!</h2>
    <% end %>
    <br>
    <hr>
  </div>

  <% @assignmentsData.each do |assignmentData| %>
      <div style='position:relative;'>
        <h3 style="text-align: center;"><%= assignmentData.assignment.name %></h3>
        <div style='position:absolute;right:0;top:0'>
          <button style="display: inline;" class="btn btn-default pull-right" data-async-href="<%= "anvil/#{assignmentData.assignment.id}/assignment" %>" >Open Assignment</button>
        </div>
      </div>

      <div style="text-align: center;">
        <div class="label label-<%= assignmentData.dueDateColorLabel %>">
          <%= assignmentData.assignment.due_date_countdown %>
        </div>
      </div>

      <br>

      <div style="text-align: center;">
        <div>

          <div class="progress">
            <div class="progress-bar progress-bar-success" style="width: <%= assignmentData.pointsPercent %>">
              <span class="">Progress</span>
            </div>
          </div>

          <!--<div class="progress text-center">-->
          <!--<div class="progress-bar progress-bar-success progress-bar-striped"-->
          <!--style="width: <%= assignmentData.extraCreditPercent %>">-->
          <!--<span class="">Extra Credit</span>-->
          <!--</div>-->
          <!--</div>-->

        </div>

      </div>

      <%= raw assignmentData.assignment.brief_markdown.html_safe %>
      <em class="pull-right">Due <%= pretty_date assignmentData.assignment.dueDate %></em>

      <br>
      <br>
      <hr>
  <% end %>
</div>

Forge/app/views/anvil/_assignment_progress.html.erb
<canvas id="myChart" width="200" height="200"></canvas>
<script>
    var ready = function() {
        var ctx = document.getElementById("myChart").getContext("2d");
        var data = <%=raw @graphData.to_json%>;
        var myDoughnutChart = new Chart(ctx).Doughnut(data, {});
    };
    $(document).ready(ready);
    $(window).bind('page:change', ready);
</script>

Forge/app/views/anvil/_getting_started.html.erb
<% content_for :for_head do %>
    <div id="flameHeader">
      <span id="dummySpan"></span>
      <div id="label">Anvil</div>
    </div>
<% end %>

<br>
<hr>

<div style='position:relative;'>
  <h2 style="text-align: center">Getting started with Anvil on <span id="osTypeText"></span></h2>
  <div style='position:absolute;right:0;top:0'>
    <div class="btn-group pull-right">
      <button id="osDropdown" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <i><span id="ddText">Wrong Platform? </span> <span class="caret"></span></i>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><a id="windowsSelect">Windows</a></li>
        <li><a id="osxSelect">OS X</a></li>
        <li><a id="otherSelect">Other</a></li>
      </ul>
    </div>
  </div>
</div>

<!-- Windows Tab -->
<div id="Windows" style="text-align: center">
  <div data-async-url="<%= anvil_win_url %>">
    <img style="max-width: 100px; margin-top: 100px; margin-bottom: 100px;" alt="Loading" src=<%= asset_path('Loading.gif') %> />
  </div>
</div>

<div id="OSX" style="text-align: center">
  <div data-async-url="<%= anvil_osx_url %>">
    <img style="max-width: 100px; margin-top: 100px; margin-bottom: 100px;" alt="Loading" src=<%= asset_path('Loading.gif') %> />
  </div>
</div>

<div id="Other" style="text-align: center">
  <div data-async-url="<%= anvil_other_url %>">
    <img style="max-width: 100px; margin-top: 100px; margin-bottom: 100px;" alt="Loading" src=<%= asset_path('Loading.gif') %> />
  </div>
</div>

Forge/app/views/anvil/_gs_osx.html.erb
<img style="width: 300px;" src=<%=asset_path('XCode/XCodeIcon.png')%> />
<P>All you need to get started is XCode, from the Apple App Store. It's that easy!
<form action='https://itunes.apple.com/us/app/xcode/id497799835?ls=1&mt=12'>
  <button class="btn btn-primary">
    <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span> Open in App Store
  </button>
</form>

<br>
<br>

<h3>What is XCode?</h3>
<p>XCode is an IDE (Integrated Development Environment) made by Apple. For now think of it as a very sophisticated text editor for code, one that knows intimately how the code works and holds the code's hand while it is running. All Anvil assignments are built to run in XCode or it's Windows counterpart, Visual Studio.</p>

<br>
<br>
<h3>What do I do with it?</h3>
<p>On Mac OSX all Anvil assignments are loaded with XCode. Simply download an assignment and double click on the .xcodeproj file. XCode will launch and open up the project.</p>
<img style="max-width: 1024px; margin-bottom: 50px;" src=<%=asset_path('XCode/XCodeJustOpened.png')%> />

<p>Welcome to XCode! Lets take a quick look at the important controls. Lets take a look at the panel controls, in the upper right corner. Click the middle button to un-hide the debugger. We will use this panel to view console output. Click the right button to hide the Utilities Panel. Anvil Assignments do not use this panel.</p>
<img style="max-width: 150px; margin-bottom: 50px;" src=<%= asset_path('XCode/XCodePaneControls.png')%> />


<p>To the left is the Navigator, where all files in this project are shown hierarchically. Note that this panel can also be hidden with the panel controls. By default it should look similar to this. Anvil Assignments can look different from each other so your mileage may vary.</p>
<img style="max-width: 300px; margin-bottom: 50px;" src=<%=asset_path('XCode/XCodeProjectExplorerClosed.png')%> />

<p>Expand out the folder with the same name as the project. In this case HelloWorldAssignment.</p>
<img style="max-width:300px; margin-bottom: 50px;" src=<%=asset_path('XCode/XCodeProjectExplorerOpen.png')%> />

<p>We found our almighty main.cpp file! All C++ executables have what is known as an 'entry point'. In this case our entry point is in main.cpp. It is where the code will start running when we click the play button. Single click main.cpp to open it in the editor panel. Double clicking the file will open it in a new window.</p>
<img style="max-width: 720px; margin-bottom: 50px;" src=<%=asset_path('XCode/XCodeCodeReady.png')%> />

<p>Hit the play button in the upper left corner. This will build your project and run it assuming there were no build errors.</p>
<img style="max-width: 100px; margin-bottom: 50px;" src=<%=asset_path('XCode/XCodeRunStopButton.png')%> />

<p>Congratulations, you just compiled and ran your first Anvil Assignment! Granted we didn't add any code so there was no output. From here you can begin working on the Anvil Assignment.</p>

<br>
<br>
<h2>Good Hunting!</h2>
<i>Remember, Search Engines are your friend. Most 'how do I do XYZ in XCode' questions have been answered online.</i>
<br>
<br>

Forge/app/views/anvil/_gs_other.html.erb
<img style="width: 300px;" src=<%=asset_path('LinuxIcon.png')%> />
<p>Sadly Scorch does not actively support any other platforms.</p>

<br>
<br>
<h3>What gives? Where is my Linux?</h3>
<p>Linux is a wonderful platform filled with wonders and frustrations. Unfortunately supporting Linux and <i>[Inset your obscure OS here]</i> means supporting a very wide range of kernels, builds, compilers, editors and so on. Scorch is fully open source and anyone is welcome to take a crack at compiling Anvil on their platform of choice. Scorch cannot provide help with such endeavors so this challenge is not for the novice.</p>

<br>
<br>
<h3>Were is the source, I got this!</h3>
<p>All source code is hosted on Github.com</p>
<br>
<form action='https://github.com/AThilenius/Scorch'>
  <button class="btn btn-default" style="width: 200px;">
    Scorch Source Code
  </button>
</form>

<br>
<br>
<h3>I did it! Compiled and running!</h3>
<p>If you wish to actively support another platform please contact Alec@Thielnius.com and we can discuss if it makes sense to add it to Forge.</p>

<br>
<br>

Forge/app/views/anvil/_gs_win.html.erb
<img style="width: 300px;" src=<%= asset_path('VisualStudio/VSIcon.png')%> />
<p>On Windows Anvil uses Microsoft Visual Studio 2012 for all Anvil Assignments. Visual Studio comes in two flavors, Express and Pro. As a students Microsoft offers the Pro version for free. It is highly recommended you get the Pro version if it is available to you.</p>

<br>
<h3>Visual Studio 2012 Pro (Recommended)</h3>
<p>The Pro version is available free for students. Head over to <a href="https://www.dreamspark.com/Product/Product.aspx?productid=44">DreamSpark.com</a> and click on <i>Get Verified</i>. Sign in with any a Microsoft account. From there you will need to provide a valid and unused .edu email address to prove you are indeed a student. Once verified download and install "Visual Studio Professional 2012".</p>


<br>
<h3>Visual Studio 2012 Express</h3>
<p>The express version can be downloaded as an ISO disk image or using the Web Installer from the <a href="http://www.microsoft.com/en-us/download/details.aspx?id=34673">Microsoft Download Center</a>. Chose one of the two after clicking Download. Use the Web Installer (wdexpress_full.exe) if you do not know what an ISO is.</p>


<br>
<br>
<h3>What is Visual Studio?</h3>
<p>Visual Studio is an IDE (Integrated Development Environment) made by Microsoft. For now think of it as a very sophisticated text editor for code, one that knows intimately how the code works and holds the code's hand while it is running. All Anvil assignments are built to run in Visual Studio or it's Mac OSX counterpart, XCode.</p>

<br>
<br>
<h3>What do I do with it?</h3>
<p>On Windows all Anvil assignments are loaded with Visual Studio 2012. Simply download an assignment and double click on the .sln file. Visual Studio will launch and open up the project.</p>
<img style="max-width: 1024px; margin-bottom: 50px;" src=<%= asset_path('VisualStudio/VSJustOpened.png')%> />


<p>Welcome to Visual Studio! To the left is the Solution Explorer, where all files in this solution are shown hierarchically. By default it should look similar to this although panels may be moved around if you picked different settings when first launching Visual Studio.</p>
<img style="max-width: 300px; margin-bottom: 50px;" src=<%= asset_path('VisualStudio/VSSolutionExplorerClosed.png')%> />

<p>Expand the Project, in this case called HelloWorld.</p>
<img style="max-width:300px; margin-bottom: 50px;" src=<%= asset_path('VisualStudio/VSSolutionExplorerOpen.png')%> />

<p>We found our almighty main.cpp file! All C++ executables have what is known as an 'entry point'. In this case our entry point is in Main.cpp. It is where the code will start running when we click run. Double click Main.cpp to open it in the editor panel.</p>
<img style="max-width: 720px; margin-bottom: 50px;" src=<%= asset_path('VisualStudio/VSCodeReady.png')%> />

<p>Go to Debug and click Start Debugging. Note that the keyboard shortcut (In this case F5) will change depending on what settings you picked when first launching Visual Studio. This will build your project and run it assuming there were no build errors.</p>
<img style="max-width: 300px; margin-bottom: 50px;" src=<%= asset_path('VisualStudio/VSStartDebugging.png')%> />

<p>Congratulations, you just compiled and ran your first Anvil Assignment! Granted we didn't add any code so there was no output. From here you can begin working on the Anvil Assignment.</p>

<br>
<br>
<h2>Good Hunting!</h2>
<i>Remember, Search Engines are your friend. Most 'how do I do XYZ in XCode' questions have been answered online.</i>
<br>
<br>

Forge/app/views/anvil/_my_anvil.html.erb
<!-- Top -->
<div style="position: absolute; top: 0px; left: 0px; right: 0px; height: 80px; background-color: orange; overflow: scroll; border-bottom: 1px solid white;">
    <button id="run_button" class="btn btn-default">Run</button>
</div>

<!-- Left -->
<div style="position: absolute; top: 80px; left: 0px; bottom: 0px; width: 250px; overflow: scroll; border-right: 1px solid white;">
  <div data-async-url=<%="anvil/2/assignment_description"%> >
    <div style="text-align: center">
      <img style="max-width: 100px; margin-top: 100px; margin-bottom: 100px;" alt="Loading" src=<%= asset_path('Loading.gif') %> />
    </div>
  </div>
</div>

<!-- Right -->
<div style="position: absolute; top: 80px; left: 250px; right: 0px; bottom: 200px; background-color: blue; overflow: scroll;">

  <div id="editor" style='width: 100%; height: 100%;'>from AnvilApi import *
Anvil.sayHello()</div>

  <script>
      var editor = ace.edit("editor");
      editor.setTheme("ace/theme/monokai");
      editor.getSession().setMode("ace/mode/python");
  </script>

</div>

<!-- Bottom -->
<div style="position: absolute; left: 250px; right: 0px; bottom: 0px; height: 200px; overflow: scroll; border-top: 1px solid white;">

  <div id="terminal" style='width: 100%; height: 100%;'>Welcome to Blaze, Alec Thilenius!
    Some other text!</div>

  <script>
      var terminal = ace.edit("terminal");
      terminal.setTheme("ace/theme/terminal");
      terminal.setReadOnly(true);
      terminal.setHighlightActiveLine(false);
      terminal.renderer.setShowGutter(false);

  </script>

</div>

Forge/app/views/anvil/getting_started.html.erb
<% content_for :for_head do %>
    <div id="flameHeader">
      <span id="dummySpan"></span>
      <div id="label">Anvil</div>
    </div>
<% end %>

<br>
<hr>

<div style='position:relative;'>
  <h2 style="text-align: center">Getting started with Anvil on <span id="osTypeText"></span></h2>
  <div style='position:absolute;right:0;top:0'>
    <div class="btn-group pull-right">
      <button id="osDropdown" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <i><span id="ddText">Wrong Platform? </span> <span class="caret"></span></i>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><a id="windowsSelect">Windows</a></li>
        <li><a id="osxSelect">OS X</a></li>
        <li><a id="otherSelect">Other</a></li>
      </ul>
    </div>
  </div>
</div>

<!-- Windows Tab -->
<div id="Windows" style="text-align: center">
  <div data-async-url="<%= anvil_win_url %>">
    <img style="max-width: 100px; margin-top: 100px; margin-bottom: 100px;" alt="Loading" src=<%= asset_path('Loading.gif') %> />
  </div>
</div>

<div id="OSX" style="text-align: center">
  <div data-async-url="<%= anvil_osx_url %>">
    <img style="max-width: 100px; margin-top: 100px; margin-bottom: 100px;" alt="Loading" src=<%= asset_path('Loading.gif') %> />
  </div>
</div>

<div id="Other" style="text-align: center">
  <div data-async-url="<%= anvil_other_url %>">
    <img style="max-width: 100px; margin-top: 100px; margin-bottom: 100px;" alt="Loading" src=<%= asset_path('Loading.gif') %> />
  </div>
</div>

Forge/app/views/anvil/show.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <meta property="og:image" content=<%=asset_path('Flame-512.png')%> />
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= meta_description %>">
  <meta name="author" content="<%= meta_author %>">
  <meta name="Keywords" content="<%= meta_keywords %>">

  <title><%= full_title(yield(:title)) %></title>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href=<%=asset_path('Flame-512.png')%> />

  <%= stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <a href="#Top"></a>
</head>
<body>

    <%= render 'my_anvil' %>

<footer>
</footer>
</body>
</html>