Forge/config/routes.rb
Rails.application.routes.draw do

  # Landing
  get 'home_page/landing' => 'home_page#landing'
  get 'home_page/landing_body' => 'home_page#landing_body'

  # Anvil
  get 'anvil/show'
  get 'anvil/list'
  get 'anvil/overview'
  get 'anvil/assignment_list' => 'anvil#assignment_list'
  get 'anvil/my_anvil' => 'anvil#my_anvil'
  get 'anvil/:id/assignment' => 'anvil#assignment'
  get 'anvil/getting_started' => 'anvil#getting_started'
  get 'anvil/osx' => 'anvil#gs_osx'
  get 'anvil/win' => 'anvil#gs_win'
  get 'anvil/other' => 'anvil#gs_other'
  get 'anvil/:id/assignment_progress' => 'anvil#assignment_progress'
  get 'anvil/:id/assignment_description' => 'anvil#assignment_description'

  get 'blaze/show'

  get 'flame/show' => 'flame#show'

  get 'minecraft/show'

  get 'students/create'
  get 'students/list'
  get 'students/new'
  get 'account' => 'account#show'
  get 'assignments/create'
  get 'assignments/createLevel'
  get 'assignments/new'
  get 'downloads/:id/proj/(*path)' => 'downloads#proj'
  get 'downloads/flame' => 'downloads#flame'
  get 'login' => 'session#show'
  get 'minecraft_accounts/create'
  get 'minecraft_accounts/list'
  get 'minecraft_accounts/new'
  get 'password' => 'password#show'
  get 'password_change' => 'password#change'
  get 'session_login' => 'session#login'
  get 'session_logout' => 'session#logout'
  post 'service/get_minecraft_session' => 'service#get_minecraft_session'
  post 'service/get_user_level_data' => 'service#get_user_level_data'
  post 'service/get_chat' => 'service#get_chat'
  post 'service/push_chat' => 'service#push_chat'
  match 'blaze/(*path)' => redirect {|params, req| "http://localhost:9886/#{params[:path]}"},  via: [:get, :post]

  resources :minecraft_accounts, :only => [:show, :destroy]
  resources :students, :only => [:show, :destroy]
  resources :assignments, :only => [:show, :destroy]

  root 'anvil#show'
end

Forge/app/controllers/students_controller.rb
class StudentsController < ApplicationController

	include SessionHelper

  def list
  	return if sessionAdminCheckFailed

    @students = User.where(:permissions => 'student').order(lastName: :desc)
  end

  def show
  	return if sessionAdminCheckFailed

  	@student = User.find(params[:id])
    if @student.nil?
      flash[:error] = "Cannot find find a student with ID: #{params[:id]}"
      redirect_to students_list_path
      return
    end
  end

  def destroy
    return if sessionAdminCheckFailed

    @student = User.find(params[:id])
    if @student.nil?
      flash[:error] = "Cannot find find the student account with ID: #{params[:id]}"
    else
      flash[:notice] = "Account #{@student.username} deleted successfully."
      @student.delete
    end

    redirect_to students_list_path
  end

  def new
    return if sessionAdminCheckFailed
  end

  def create

    return if sessionAdminCheckFailed
    didPass = true
    failureString = ''

    if params[:username].nil? or params[:username].empty?
      failureString += 'Zero length user name. '
      didPass = false
    end

    if params[:firstName].nil? or params[:firstName].empty?
      failureString += 'Zero length first name. '
      didPass = false
    end

    if params[:lastName].nil? or params[:lastName].empty?
      failureString += 'Zero length last name. '
      didPass = false
    end

    if params[:studentID].nil? or params[:studentID].empty?
      failureString += 'Zero length student ID. '
      didPass = false
    end

    if params[:arenaLocation].nil? or params[:arenaLocation].empty?
      failureString += 'Zero length Arena Location. '
      didPass = false
    end

    # Check existence
    if didPass
      user = User.create(username: params[:username],
                        firstName: params[:firstName],
                        lastName: params[:lastName],
                        studentID: params[:studentID],
                        permissions: 'student',
                        password: SecureRandom.uuid.split('-')[4],
                        guid: SecureRandom.uuid,
                        arenaLocation: params[:arenaLocation])

      flash[:notice] = "Account #{user.username} Created Successfully."
      redirect_to students_new_path
    end

    if not didPass
      flash[:error] = failureString
      redirect_to students_new_path
    end

  end
end

Forge/app/helpers/students_helper.rb
module StudentsHelper
end

Forge/app/views/students/list.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Students

      <div class="btn-group btn-group-xs pull-right">
        <a type="button" class="btn btn-default" href=<%=students_new_path%>>Add</a>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
          Filter
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">All</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Free</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Allocated</a></li>
        </ul>
      </div>

    </h3>

  </div>
  <div class="panel-body">

    <ul class="list-group">
      <% @students.each do |user| %>

          <a class="list-group-item" href=<%= student_path(user.id) %>>
            <%= "#{user.firstName} #{user.lastName}" %>
          </a>

      <% end %>
    </ul>

  </div>
</div>

Forge/app/views/students/new.html.erb
<form id="createForm" role="form-signin" action="create">
  <div class="thinWindow">
    <h3 class="text-center"> Student Info </h3>
    <hr>

    <div class="form-group">
      <label for="username">CU Login</label>
      <input class="form-control" type="username" name="username" placeholder="CU Login">
    </div>

    <div class="form-group">
      <label for="firstName">First Name</label>
      <input class="form-control" type="firstName" name="firstName" placeholder="First Name">
    </div>

    <div class="form-group">
      <label for="lastName">Last Name</label>
      <input class="form-control" type="lastName" name="lastName" placeholder="Last Name">
    </div>

    <div class="form-group">
      <label for="studentID">Student ID</label>
      <input class="form-control" type="studentID" name="studentID" placeholder="Student ID">
    </div>

    <div class="form-group">
      <label for="arenaLocation">Arena Location</label>
      <input class="form-control" type="arenaLocation" name="arenaLocation" placeholder="Ex: 0, 0, 0">
    </div>

    <button type="submit" class="btn btn-default btn-primary autoWidth">Create</button>

    <hr>
  </div>
</form>
<div class="thinWindow">
  <p class="small text-center">A password will be automatically generated.</p>
</div>

Forge/app/views/students/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      Student: <%= @student.username %>
    </h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <img height="250" width="250" src=<%=asset_path('Flame-512.png')%> />
      </div>
      <div class="col-md-4">

        <dl class="dl-horizontal">
          <dt>CU Login:</dt>
          <dd><%= @student.username %></dd>
        </dl>

        <dl class="dl-horizontal">
          <dt>First Name:</dt>
          <dd><%= @student.firstName %></dd>
        </dl>

        <dl class="dl-horizontal">
          <dt>Last Name:</dt>
          <dd><%= @student.lastName %></dd>
        </dl>

        <dl class="dl-horizontal">
          <dt>Password:</dt>
          <dd><%= @student.password %></dd>
        </dl>

        <dl class="dl-horizontal">
          <dt>Student ID:</dt>
          <dd><%= @student.studentID %></dd>
        </dl>

      </div>
      <div class="col-md-4">
        <%= link_to "Delete Account", student_path(@student.id), :class => 'btn btn-danger autoWidth', :method => :delete %>
      </div>
    </div>

  </div>
</div>