Forge/config/routes.rb
Rails.application.routes.draw do

  # Landing
  get 'home_page/landing' => 'home_page#landing'
  get 'home_page/landing_body' => 'home_page#landing_body'

  # Anvil
  get 'anvil/show'
  get 'anvil/list'
  get 'anvil/overview'
  get 'anvil/assignment_list' => 'anvil#assignment_list'
  get 'anvil/my_anvil' => 'anvil#my_anvil'
  get 'anvil/:id/assignment' => 'anvil#assignment'
  get 'anvil/getting_started' => 'anvil#getting_started'
  get 'anvil/osx' => 'anvil#gs_osx'
  get 'anvil/win' => 'anvil#gs_win'
  get 'anvil/other' => 'anvil#gs_other'
  get 'anvil/:id/assignment_progress' => 'anvil#assignment_progress'
  get 'anvil/:id/assignment_description' => 'anvil#assignment_description'

  get 'blaze/show'

  get 'flame/show' => 'flame#show'

  get 'minecraft/show'

  get 'students/create'
  get 'students/list'
  get 'students/new'
  get 'account' => 'account#show'
  get 'assignments/create'
  get 'assignments/createLevel'
  get 'assignments/new'
  get 'downloads/:id/proj/(*path)' => 'downloads#proj'
  get 'downloads/flame' => 'downloads#flame'
  get 'login' => 'session#show'
  get 'minecraft_accounts/create'
  get 'minecraft_accounts/list'
  get 'minecraft_accounts/new'
  get 'password' => 'password#show'
  get 'password_change' => 'password#change'
  get 'session_login' => 'session#login'
  get 'session_logout' => 'session#logout'
  post 'service/get_minecraft_session' => 'service#get_minecraft_session'
  post 'service/get_user_level_data' => 'service#get_user_level_data'
  post 'service/get_chat' => 'service#get_chat'
  post 'service/push_chat' => 'service#push_chat'
  match 'blaze/(*path)' => redirect {|params, req| "http://localhost:9886/#{params[:path]}"},  via: [:get, :post]

  resources :minecraft_accounts, :only => [:show, :destroy]
  resources :students, :only => [:show, :destroy]
  resources :assignments, :only => [:show, :destroy]

  root 'anvil#show'
end

Forge/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

Forge/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <meta property="og:image" content=<%=asset_path('Flame-512.png')%> />
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= meta_description %>">
  <meta name="author" content="<%= meta_author %>">
  <meta name="Keywords" content="<%= meta_keywords %>">

  <title><%= full_title(yield(:title)) %></title>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href=<%=asset_path('Flame-512.png')%> />

  <%= stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <a href="#Top"></a>

  <% if content_for? :for_head %>
      <%= yield :for_head %>
  <% end %>

</head>
<body>

<!--JavaScript Globals-->
<script>
    var BlazeIp = "54.67.38.67";
    var BlazeJsonPort = 80;
    var BlazeJsonPath = "/json";
</script>

<div id="custom-bootstrap-menu" class="navbar-fixed-top navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse navbar-menubuilder">
        <ul class="nav navbar-nav pull-right">
          <li class="<%= 'active' if current_page?(anvil_show_path) or @assignment != nil %>">
            <a href=<%= anvil_show_path %>>Anvil
              <% assignmentsCount = pending_assignments_count %>
              <% if assignmentsCount != 0 %>
                  <span class="badge"><%= pending_assignments_count %></span>
              <% end %>
            </a>
          <li class="<%= 'active' if current_page?(flame_show_path) %>"><a href=<%=flame_show_path%>>Flame</a>

            <% if sessionIsLoggedIn %>
                <!-- Session Dropdown -->
              <li class="dropdown <%= 'active' if current_page?(account_path) %>">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  <%= "#{sessionGetUser.firstName} #{sessionGetUser.lastName}" %><span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="<%= account_path %>">Account</a></li>
                  <li class="divider"></li>
                  <li><a href="<%= session_logout_path %>">Sign Out</a></li>
                </ul>
              </li>
              <!-- /Seesion Dropdown -->

          <% else %>
              <li class="<%= 'active' if current_page?(login_path) %>"><%= link_to "Sign In", login_path %></li>
          <% end %>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->

<div class="container">

  <!-- Render Notification -->
  <%= render 'layouts/messages' %>

  <%= yield %>

  <footer>
    <hr>
    <br>
    <p class="pull-right">
      <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
    </p>
    <p>
      &copy; <%= Time.now.year %> <%= site_name %>
      &bull;
      <%= link_to "Privacy", root_path %></li>
      &bull;
      <%= link_to "Terms", root_path %></li>
      &bull;
      Alec@Thilenius.com
    </p>
    <br>
  </footer>

</div> <!-- /container -->

</body>
</html>