Forge/config/routes.rb
Rails.application.routes.draw do

  # Landing
  get 'home_page/landing' => 'home_page#landing'
  get 'home_page/landing_body' => 'home_page#landing_body'

  # Anvil
  get 'anvil/show'
  get 'anvil/list'
  get 'anvil/overview'
  get 'anvil/assignment_list' => 'anvil#assignment_list'
  get 'anvil/my_anvil' => 'anvil#my_anvil'
  get 'anvil/:id/assignment' => 'anvil#assignment'
  get 'anvil/getting_started' => 'anvil#getting_started'
  get 'anvil/osx' => 'anvil#gs_osx'
  get 'anvil/win' => 'anvil#gs_win'
  get 'anvil/other' => 'anvil#gs_other'
  get 'anvil/:id/assignment_progress' => 'anvil#assignment_progress'
  get 'anvil/:id/assignment_description' => 'anvil#assignment_description'

  get 'blaze/show'

  get 'flame/show' => 'flame#show'

  get 'minecraft/show'

  get 'students/create'
  get 'students/list'
  get 'students/new'
  get 'account' => 'account#show'
  get 'assignments/create'
  get 'assignments/createLevel'
  get 'assignments/new'
  get 'downloads/:id/proj/(*path)' => 'downloads#proj'
  get 'downloads/flame' => 'downloads#flame'
  get 'login' => 'session#show'
  get 'minecraft_accounts/create'
  get 'minecraft_accounts/list'
  get 'minecraft_accounts/new'
  get 'password' => 'password#show'
  get 'password_change' => 'password#change'
  get 'session_login' => 'session#login'
  get 'session_logout' => 'session#logout'
  post 'service/get_minecraft_session' => 'service#get_minecraft_session'
  post 'service/get_user_level_data' => 'service#get_user_level_data'
  post 'service/get_chat' => 'service#get_chat'
  post 'service/push_chat' => 'service#push_chat'
  match 'blaze/(*path)' => redirect {|params, req| "http://localhost:9886/#{params[:path]}"},  via: [:get, :post]

  resources :minecraft_accounts, :only => [:show, :destroy]
  resources :students, :only => [:show, :destroy]
  resources :assignments, :only => [:show, :destroy]

  root 'anvil#show'
end

Forge/app/models/minecraft_account.rb
class MinecraftAccount < ActiveRecord::Base
end

Forge/app/controllers/minecraft_accounts_controller.rb
class MinecraftAccountsController < ApplicationController

	include SessionHelper

  def list
  	return if sessionAdminCheckFailed

	end

	def destroy
		return if sessionAdminCheckFailed

		@mcAccount = MinecraftAccount.find(params[:id])
		if @mcAccount.nil?
			flash[:error] = "Cannot find find the minecraft account ID: #{params[:id]}"
		else
			flash[:notice] = "Account #{@mcAccount.username} deleted successfully."
			@mcAccount.delete!
		end

		redirect_to minecraft_accounts_list_path
	end

  def show
  	return if sessionAdminCheckFailed

    @mcAccount = MinecraftAccount.find(params[:id])
    if @mcAccount.nil?
      flash[:error] = "Cannot find find the minecraft account ID: #{params[:id]}"
      redirect_to minecraft_accounts_list_path
    end
  end

  def new
  	return if sessionAdminCheckFailed
  end

  def create
  	return if sessionAdminCheckFailed
  	didPass = true
  	failureString = ""

  	if params[:mcpassword].nil? or params[:mcpassword].empty?
			failureString += 'Zero length password. '
			didPass = false
		end

		if params[:mcusername].nil? or params[:mcusername].empty?
			failureString += 'Zero length user name. '
			didPass = false
		end

  	# Check existence
  	if didPass
			# Generate a UUID for the account
			account = MinecraftAccount.create(username: params[:mcusername],
																				password: params[:mcpassword],
																				state: 'free')

			flash[:notice] = "Account #{account.username} Created Successfully."
			redirect_to minecraft_accounts_list_path
  	end
  	
		if not didPass
			flash[:error] = failureString
			redirect_to minecraft_accounts_new_path
		end

  end
end

Forge/app/helpers/minecraft_accounts_helper.rb
module MinecraftAccountsHelper


end

Forge/app/views/minecraft_accounts/list.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Statistics</h3>

  </div>
  <div class="panel-body">
    <div class="progress">
      <div class="progress-bar progress-bar-danger" style="width: 70%">
        <span class="">Allocated</span>
      </div>
      <div class="progress-bar progress-bar-success" style="width: 30%">
        <span class="">Free</span>
      </div>
    </div>

  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Accounts

      <div class="btn-group btn-group-xs pull-right">
        <a type="button" class="btn btn-default" href=<%=minecraft_accounts_new_path%>>Add</a>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
          Filter
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">All</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Free</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Allocated</a></li>
        </ul>
      </div>

    </h3>

  </div>
  <div class="panel-body">

    <ul class="list-group">
      <% MinecraftAccount.find_each do |mcAccount| %>

          <a class="list-group-item" href=<%= minecraft_account_path(mcAccount.id) %>>
            <%= mcAccount.username.upcase %> - <%= mcAccount.username %>
          </a>

      <% end %>
    </ul>

  </div>
</div>

Forge/app/views/minecraft_accounts/new.html.erb
<form id="createForm" role="form-signin" action="create">
	<div class="thinWindow">
		<h3 class="text-center"> Minecraft Account Info </h3>
		<hr></hr>
		<div class="form-group">
			<label for="mcusername">Account User Name</label>
			<input id="unField" class="form-control" type="mcusername" name="mcusername" placeholder="Account User Name">
		</div>
		<div class="form-group">
			<label for="mcpassword">Account Password</label>
			<input id="pwField" class="form-control" type="password" name="mcpassword" placeholder="Account Password">
		</div>
		<button type="submit" class="btn btn-default btn-primary autoWidth">Create</button>
		<hr></hr>
	</div>
</form>
<div class="thinWindow">

	<div id="verifyDiv" class="hidden">
		<h4> Verifying Account Info </h4>

		<div class="progress">
		  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
		    <span class="sr-only"></span>
		  </div>
		</div>
	</div>

	<p class="small text-center">Forge, your portal to Scorch</p>
</div>

Forge/app/views/minecraft_accounts/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      Minecraft Account: <%= @mcAccount.username %>
    </h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <img height="250" width="250" src=<%=asset_path('MinecraftCube.png')%> />
      </div>
      <div class="col-md-4">

        <dl class="dl-horizontal">
          <dt>User Name:</dt>
          <dd><%= @mcAccount.username %></dd>
        </dl>

        <dl class="dl-horizontal">
          <dt>Password:</dt>
          <dd><a href=<%= password_path %>>Change</a></dd>
        </dl>

        <dl class="dl-horizontal">
          <dt>State:</dt>
          <dd><%= @mcAccount.state %></dd>
        </dl>

      </div>
      <div class="col-md-4">
        <%= link_to "Delete Account", minecraft_account_path(@mcAccount.id), :class => 'btn btn-danger autoWidth', :method => :delete %>
      </div>
    </div>

  </div>
</div>